# Generated by Django 5.0.1 on 2026-04-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="admissionscore",
            new_name="admissions__year_8c0ff9_idx",
            old_name="admissions_admission_year_idx",
        ),
        migrations.RenameIndex(
            model_name="admissionscore",
            new_name="admissions__univers_becdb1_idx",
            old_name="admissions_admission_prog_year_idx",
        ),
        migrations.RenameIndex(
            model_name="universityprogram",
            new_name="admissions__major_c_62026b_idx",
            old_name="admissions_univers_major_idx",
        ),
        migrations.RenameIndex(
            model_name="universityprogram",
            new_name="admissions__univers_122c31_idx",
            old_name="admissions_univers_univ_code_idx",
        ),
    ]
