# Generated by Django 5.0.1 on 2026-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_majorcatalog_subject_groups_m2m"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="field",
            options={
                "ordering": ["code"],
                "verbose_name": "NgÃ\xa0nh há»\x8dc",
                "verbose_name_plural": "CÃ¡c ngÃ\xa0nh há»\x8dc",
            },
        ),
        migrations.AlterModelOptions(
            name="majorcatalog",
            options={
                "ordering": ["code"],
                "verbose_name": "ChuyÃªn ngÃ\xa0nh",
                "verbose_name_plural": "CÃ¡c chuyÃªn ngÃ\xa0nh",
            },
        ),
        migrations.AlterModelOptions(
            name="majorsubjectgroup",
            options={
                "verbose_name": "ChuyÃªn ngÃ\xa0nh - NhÃ³m mÃ´n",
                "verbose_name_plural": "ChuyÃªn ngÃ\xa0nh - NhÃ³m mÃ´n",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectgroup",
            options={
                "ordering": ["code"],
                "verbose_name": "NhÃ³m mÃ´n",
                "verbose_name_plural": "CÃ¡c nhÃ³m mÃ´n",
            },
        ),
        migrations.AlterField(
            model_name="majorsubjectgroup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
