# Generated by Django 5.0.1 on 2026-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0002_add_region_active_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["name"],
                "verbose_name": "Tá»‰nh",
                "verbose_name_plural": "Tá»‰nh/ThÃ\xa0nh phá»‘",
            },
        ),
        migrations.AlterModelOptions(
            name="university",
            options={
                "ordering": ["name"],
                "verbose_name": "TrÆ°á»\x9dng Ä‘áº¡i há»\x8dc",
                "verbose_name_plural": "CÃ¡c trÆ°á»\x9dng Ä‘áº¡i há»\x8dc",
            },
        ),
        migrations.RenameIndex(
            model_name="province",
            new_name="universitie_region_58c2bc_idx",
            old_name="univ_province_region_idx",
        ),
        migrations.RenameIndex(
            model_name="university",
            new_name="universitie_provinc_b49b64_idx",
            old_name="universities_universit_province_idx",
        ),
        migrations.RenameIndex(
            model_name="university",
            new_name="universitie_type_5c101e_idx",
            old_name="universities_universit_type_idx",
        ),
        migrations.RenameIndex(
            model_name="university",
            new_name="universitie_type_10f0ee_idx",
            old_name="universities_universit_type_prov_idx",
        ),
        migrations.RenameIndex(
            model_name="university",
            new_name="universitie_is_acti_d3dcd7_idx",
            old_name="univ_active_idx",
        ),
        migrations.RenameIndex(
            model_name="university",
            new_name="universitie_is_acti_c0abac_idx",
            old_name="univ_active_type_prov_idx",
        ),
        migrations.AlterField(
            model_name="province",
            name="region",
            field=models.CharField(
                choices=[("Báº¯c", "Báº¯c"), ("Trung", "Trung"), ("Nam", "Nam")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="type",
            field=models.CharField(
                choices=[
                    ("cÃ´ng_láº\xadp", "CÃ´ng láº\xadp"),
                    ("dÃ¢n_láº\xadp", "DÃ¢n láº\xadp"),
                    ("quÃ¢n_sá»±", "QuÃ¢n sá»±"),
                ],
                max_length=20,
            ),
        ),
    ]
