# Generated by Django 5.0.1 on 2026-04-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "universities",
            "0003_alter_province_options_alter_university_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="province",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="university",
            options={"ordering": ["name"]},
        ),
    ]
